// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: order.proto

package pb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Stock         int64                  `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProductRequest) Reset() {
	*x = AddProductRequest{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductRequest) ProtoMessage() {}

func (x *AddProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductRequest.ProtoReflect.Descriptor instead.
func (*AddProductRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *AddProductRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *AddProductRequest) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type CommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *CommonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDetailRequest) Reset() {
	*x = DeleteDetailRequest{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDetailRequest) ProtoMessage() {}

func (x *DeleteDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDetailRequest.ProtoReflect.Descriptor instead.
func (*DeleteDetailRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteDetailRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UserCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount        float32                `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Items         []*ItemCart            `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCartResponse) Reset() {
	*x = UserCartResponse{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCartResponse) ProtoMessage() {}

func (x *UserCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCartResponse.ProtoReflect.Descriptor instead.
func (*UserCartResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *UserCartResponse) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *UserCartResponse) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UserCartResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UserCartResponse) GetItems() []*ItemCart {
	if x != nil {
		return x.Items
	}
	return nil
}

type ItemCart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     int32                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,3,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float32                `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemCart) Reset() {
	*x = ItemCart{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemCart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemCart) ProtoMessage() {}

func (x *ItemCart) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemCart.ProtoReflect.Descriptor instead.
func (*ItemCart) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *ItemCart) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ItemCart) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ItemCart) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *ItemCart) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ItemCart) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type UserCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCartRequest) Reset() {
	*x = UserCartRequest{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCartRequest) ProtoMessage() {}

func (x *UserCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCartRequest.ProtoReflect.Descriptor instead.
func (*UserCartRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

type PlaceOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderRequest) Reset() {
	*x = PlaceOrderRequest{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderRequest) ProtoMessage() {}

func (x *PlaceOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderRequest.ProtoReflect.Descriptor instead.
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *PlaceOrderRequest) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type PlaceOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentLink   string                 `protobuf:"bytes,1,opt,name=payment_link,json=paymentLink,proto3" json:"payment_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderResponse) Reset() {
	*x = PlaceOrderResponse{}
	mi := &file_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderResponse) ProtoMessage() {}

func (x *PlaceOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderResponse.ProtoReflect.Descriptor instead.
func (*PlaceOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7}
}

func (x *PlaceOrderResponse) GetPaymentLink() string {
	if x != nil {
		return x.PaymentLink
	}
	return ""
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\aorderpb\x1a\x1bbuf/validate/validate.proto\x1a\x1bgoogle/protobuf/empty.proto\"Z\n" +
	"\x11AddProductRequest\x12&\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\tproductId\x12\x1d\n" +
	"\x05stock\x18\x02 \x01(\x03B\a\xbaH\x04\"\x02 \x00R\x05stock\"*\n" +
	"\x0eCommonResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"%\n" +
	"\x13DeleteDetailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x86\x01\n" +
	"\x10UserCartResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x05R\aorderId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x02R\x06amount\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12'\n" +
	"\x05items\x18\x04 \x03(\v2\x11.orderpb.ItemCartR\x05items\"\x8e\x01\n" +
	"\bItemCart\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x05R\tproductId\x12!\n" +
	"\fproduct_name\x18\x03 \x01(\tR\vproductName\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x02R\x05price\"\x11\n" +
	"\x0fUserCartRequest\".\n" +
	"\x11PlaceOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x05R\aorderId\"7\n" +
	"\x12PlaceOrderResponse\x12!\n" +
	"\fpayment_link\x18\x01 \x01(\tR\vpaymentLink2\xab\x02\n" +
	"\fOrderService\x12C\n" +
	"\n" +
	"AddProduct\x12\x1a.orderpb.AddProductRequest\x1a\x17.orderpb.CommonResponse\"\x00\x12G\n" +
	"\fDeleteDetail\x12\x1c.orderpb.DeleteDetailRequest\x1a\x17.orderpb.CommonResponse\"\x00\x12D\n" +
	"\vGetUserCart\x12\x18.orderpb.UserCartRequest\x1a\x19.orderpb.UserCartResponse\"\x00\x12G\n" +
	"\n" +
	"PlaceOrder\x12\x1a.orderpb.PlaceOrderRequest\x1a\x1b.orderpb.PlaceOrderResponse\"\x00B\x82\x01\n" +
	"\vcom.orderpbB\n" +
	"OrderProtoP\x01Z+github.com/vietquan-37/order-service/pkg/pb\xa2\x02\x03OXX\xaa\x02\aOrderpb\xca\x02\aOrderpb\xe2\x02\x13Orderpb\\GPBMetadata\xea\x02\aOrderpbb\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_order_proto_goTypes = []any{
	(*AddProductRequest)(nil),   // 0: orderpb.AddProductRequest
	(*CommonResponse)(nil),      // 1: orderpb.CommonResponse
	(*DeleteDetailRequest)(nil), // 2: orderpb.DeleteDetailRequest
	(*UserCartResponse)(nil),    // 3: orderpb.UserCartResponse
	(*ItemCart)(nil),            // 4: orderpb.ItemCart
	(*UserCartRequest)(nil),     // 5: orderpb.UserCartRequest
	(*PlaceOrderRequest)(nil),   // 6: orderpb.PlaceOrderRequest
	(*PlaceOrderResponse)(nil),  // 7: orderpb.PlaceOrderResponse
}
var file_order_proto_depIdxs = []int32{
	4, // 0: orderpb.UserCartResponse.items:type_name -> orderpb.ItemCart
	0, // 1: orderpb.OrderService.AddProduct:input_type -> orderpb.AddProductRequest
	2, // 2: orderpb.OrderService.DeleteDetail:input_type -> orderpb.DeleteDetailRequest
	5, // 3: orderpb.OrderService.GetUserCart:input_type -> orderpb.UserCartRequest
	6, // 4: orderpb.OrderService.PlaceOrder:input_type -> orderpb.PlaceOrderRequest
	1, // 5: orderpb.OrderService.AddProduct:output_type -> orderpb.CommonResponse
	1, // 6: orderpb.OrderService.DeleteDetail:output_type -> orderpb.CommonResponse
	3, // 7: orderpb.OrderService.GetUserCart:output_type -> orderpb.UserCartResponse
	7, // 8: orderpb.OrderService.PlaceOrder:output_type -> orderpb.PlaceOrderResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
