// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: payment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentLinkResponse) Reset() {
	*x = PaymentLinkResponse{}
	mi := &file_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentLinkResponse) ProtoMessage() {}

func (x *PaymentLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentLinkResponse.ProtoReflect.Descriptor instead.
func (*PaymentLinkResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentLinkResponse) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type PaymentLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Customer      *CustomerInfo          `protobuf:"bytes,2,opt,name=customer,proto3" json:"customer,omitempty"`
	Amount        float32                `protobuf:"fixed32,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Items         []*Items               `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentLinkRequest) Reset() {
	*x = PaymentLinkRequest{}
	mi := &file_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentLinkRequest) ProtoMessage() {}

func (x *PaymentLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentLinkRequest.ProtoReflect.Descriptor instead.
func (*PaymentLinkRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentLinkRequest) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *PaymentLinkRequest) GetCustomer() *CustomerInfo {
	if x != nil {
		return x.Customer
	}
	return nil
}

func (x *PaymentLinkRequest) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentLinkRequest) GetItems() []*Items {
	if x != nil {
		return x.Items
	}
	return nil
}

type CustomerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    int32                  `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	CustomerName  string                 `protobuf:"bytes,2,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	CustomerEmail string                 `protobuf:"bytes,3,opt,name=customer_email,json=customerEmail,proto3" json:"customer_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerInfo) Reset() {
	*x = CustomerInfo{}
	mi := &file_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerInfo) ProtoMessage() {}

func (x *CustomerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerInfo.ProtoReflect.Descriptor instead.
func (*CustomerInfo) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{2}
}

func (x *CustomerInfo) GetCustomerId() int32 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *CustomerInfo) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *CustomerInfo) GetCustomerEmail() string {
	if x != nil {
		return x.CustomerEmail
	}
	return ""
}

type Items struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float32                `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Items) Reset() {
	*x = Items{}
	mi := &file_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Items) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Items) ProtoMessage() {}

func (x *Items) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Items.ProtoReflect.Descriptor instead.
func (*Items) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{3}
}

func (x *Items) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *Items) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *Items) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Items) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_payment_proto protoreflect.FileDescriptor

const file_payment_proto_rawDesc = "" +
	"\n" +
	"\rpayment.proto\x12\tpaymentpb\")\n" +
	"\x13PaymentLinkResponse\x12\x12\n" +
	"\x04link\x18\x01 \x01(\tR\x04link\"\xa4\x01\n" +
	"\x12PaymentLinkRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x05R\aorderId\x123\n" +
	"\bcustomer\x18\x02 \x01(\v2\x17.paymentpb.CustomerInfoR\bcustomer\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x02R\x06amount\x12&\n" +
	"\x05items\x18\x04 \x03(\v2\x10.paymentpb.ItemsR\x05items\"{\n" +
	"\fCustomerInfo\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\x05R\n" +
	"customerId\x12#\n" +
	"\rcustomer_name\x18\x02 \x01(\tR\fcustomerName\x12%\n" +
	"\x0ecustomer_email\x18\x03 \x01(\tR\rcustomerEmail\"{\n" +
	"\x05Items\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05R\tproductId\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x02R\x05price2f\n" +
	"\x0ePaymentService\x12T\n" +
	"\x11CreatePaymentLink\x12\x1d.paymentpb.PaymentLinkRequest\x1a\x1e.paymentpb.PaymentLinkResponse\"\x00B\x8e\x01\n" +
	"\rcom.paymentpbB\fPaymentProtoP\x01Z+github.com/vietquan-37/order-service/pkg/pb\xa2\x02\x03PXX\xaa\x02\tPaymentpb\xca\x02\tPaymentpb\xe2\x02\x15Paymentpb\\GPBMetadata\xea\x02\tPaymentpbb\x06proto3"

var (
	file_payment_proto_rawDescOnce sync.Once
	file_payment_proto_rawDescData []byte
)

func file_payment_proto_rawDescGZIP() []byte {
	file_payment_proto_rawDescOnce.Do(func() {
		file_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)))
	})
	return file_payment_proto_rawDescData
}

var file_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_payment_proto_goTypes = []any{
	(*PaymentLinkResponse)(nil), // 0: paymentpb.PaymentLinkResponse
	(*PaymentLinkRequest)(nil),  // 1: paymentpb.PaymentLinkRequest
	(*CustomerInfo)(nil),        // 2: paymentpb.CustomerInfo
	(*Items)(nil),               // 3: paymentpb.Items
}
var file_payment_proto_depIdxs = []int32{
	2, // 0: paymentpb.PaymentLinkRequest.customer:type_name -> paymentpb.CustomerInfo
	3, // 1: paymentpb.PaymentLinkRequest.items:type_name -> paymentpb.Items
	1, // 2: paymentpb.PaymentService.CreatePaymentLink:input_type -> paymentpb.PaymentLinkRequest
	0, // 3: paymentpb.PaymentService.CreatePaymentLink:output_type -> paymentpb.PaymentLinkResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_payment_proto_init() }
func file_payment_proto_init() {
	if File_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_proto_goTypes,
		DependencyIndexes: file_payment_proto_depIdxs,
		MessageInfos:      file_payment_proto_msgTypes,
	}.Build()
	File_payment_proto = out.File
	file_payment_proto_goTypes = nil
	file_payment_proto_depIdxs = nil
}
