version: '3.9'
services:
  consul:
    image: hashicorp/consul
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0 
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    restart: always
    networks:
      - microservice-go
  api-gateway:
    image: vietquandeptrai/api-gateway
    ports:
      - "6969:6969"
    environment:
      - CONSUL_ADDR=consul:8500
      - GATEWAY_PORT=api-gateway:6969
      - AUTH_SERVICE_NAME=auth-svc
      - PRODUCT_SERVICE_NAME=product-svc
      - ORDER_SERVICE_NAME=order-svc
      - SERVICE_NAME=api-gateway
    restart: always
    depends_on:
      - consul
      - auth-svc
      - product-svc
      - order-svc
    networks:
      - microservice-go
  product-svc:
    image: vietquandeptrai/product-svc

    environment:
      - CONSUL_ADDR=consul:8500
      - DB_SOURCE=postgresql://postgres:12345@product-db:5432/product_db?sslmode=disable
      - GRPC_SERVER_ADDRESS=product-svc:5052
      - SERVICE_NAME=product-svc
      - AUTH_SERVICE_NAME=auth-svc

    restart: always
    depends_on:
      - consul
      - product-db
    networks:
      - microservice-go
  order-svc:
    image: vietquandeptrai/order-svc
    ports:
      - "5054:5054"
    environment:
      - CONSUL_ADDR=consul:8500
      - DB_SOURCE=postgresql://postgres:12345@order-db:5432/order_db?sslmode=disable
      - GRPC_SERVER_ADDRESS=order-svc:5054
      - SERVICE_NAME=order-svc
      - AUTH_SERVICE_NAME=auth
      - PRODUCT_SERVICE_NAME=product-svc
    depends_on:
      - consul
      - auth-svc
      - product-svc
      - order-db
    restart: always
    networks:
      - microservice-go
  auth-svc:
    image: vietquandeptrai/auth-svc
    ports:
      - "5051:5051"
    environment:
      - CONSUL_ADDR=consul:8500
      - DB_SOURCE=postgresql://postgres:12345@auth-db:5432/auth_db?sslmode=disable
      - GRPC_SERVER_ADDRESS=auth-svc:5051
      - JWT_SECRET=dmlldHF1YW5kZXB0cmFp
      - ADMIN_USERNAME=bubakush20099@gmail.com
      - ADMIN_PASSWORD=123
      - SERVICE_NAME=auth-svc
    restart: always
    depends_on:
      - consul
      - auth-db
    networks:
      - microservice-go
  auth-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=auth_db
    ports:
      - "5431:5432"
    volumes:
      - auth-data:/var/lib/postgresql/data
    networks:
      - microservice-go
  product-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=product_db
    ports:
      - "5430:5432"
    volumes:
      - product-data:/var/lib/postgresql/data
    networks:
      - microservice-go

  order-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=order_db
    ports:
      - "5429:5432"
    volumes:
      - order-data:/var/lib/postgresql/data
    networks:
      - microservice-go

  nginx:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-gateway
    networks:
      - microservice-go

networks:
  microservice-go:
    driver: bridge
volumes:
  auth-data:
  product-data:
  order-data:



